name: Test

on:
  push:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/test.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  integration-test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - "1.88.0"
          - stable
        os-arch:
          - ubuntu-24.04-x86_64
          - ubuntu-24.04-aarch64
          - macos-x86_64
          - macos-aarch64
          - windows-x86_64
        include:
          - os-arch: ubuntu-24.04-x86_64
            runner: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os-arch: ubuntu-24.04-aarch64
            runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - os-arch: macos-x86_64
            runner: macos-26-intel
            target: x86_64-apple-darwin
          - os-arch: macos-aarch64
            runner: macos-26
            target: aarch64-apple-darwin
          - os-arch: windows-x86_64
            runner: windows-2025
            target: x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
      - run: cargo test --all-targets --target ${{ matrix.target }}
